//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  hero: Hero;
  heroConnection: HeroConnection;
  service: Service;
  serviceConnection: ServiceConnection;
  testimonial: Testimonial;
  testimonialConnection: TestimonialConnection;
  painCard: PainCard;
  painCardConnection: PainCardConnection;
  result: Result;
  resultConnection: ResultConnection;
  techCard: TechCard;
  techCardConnection: TechCardConnection;
  sistemaCard: SistemaCard;
  sistemaCardConnection: SistemaCardConnection;
  procesoStep: ProcesoStep;
  procesoStepConnection: ProcesoStepConnection;
  contact: Contact;
  contactConnection: ContactConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHeroArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHeroConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HeroFilter>;
};


export type QueryServiceArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServiceConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiceFilter>;
};


export type QueryTestimonialArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTestimonialConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialFilter>;
};


export type QueryPainCardArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPainCardConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PainCardFilter>;
};


export type QueryResultArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryResultConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResultFilter>;
};


export type QueryTechCardArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTechCardConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TechCardFilter>;
};


export type QuerySistemaCardArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySistemaCardConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SistemaCardFilter>;
};


export type QueryProcesoStepArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProcesoStepConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProcesoStepFilter>;
};


export type QueryContactArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
};

export type DocumentFilter = {
  hero?: InputMaybe<HeroFilter>;
  service?: InputMaybe<ServiceFilter>;
  testimonial?: InputMaybe<TestimonialFilter>;
  painCard?: InputMaybe<PainCardFilter>;
  result?: InputMaybe<ResultFilter>;
  techCard?: InputMaybe<TechCardFilter>;
  sistemaCard?: InputMaybe<SistemaCardFilter>;
  procesoStep?: InputMaybe<ProcesoStepFilter>;
  contact?: InputMaybe<ContactFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Hero | Service | Testimonial | PainCard | Result | TechCard | SistemaCard | ProcesoStep | Contact | Folder;

export type HeroStats = {
  __typename?: 'HeroStats';
  number?: Maybe<Scalars['String']['output']>;
  suffix?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type Hero = Node & Document & {
  __typename?: 'Hero';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  accentBlue?: Maybe<Scalars['String']['output']>;
  accentRose?: Maybe<Scalars['String']['output']>;
  sub1?: Maybe<Scalars['String']['output']>;
  sub2?: Maybe<Scalars['String']['output']>;
  ctaPrimary?: Maybe<Scalars['String']['output']>;
  ctaSecondary?: Maybe<Scalars['String']['output']>;
  stats?: Maybe<Array<Maybe<HeroStats>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HeroStatsFilter = {
  number?: InputMaybe<StringFilter>;
  suffix?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type HeroFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  accentBlue?: InputMaybe<StringFilter>;
  accentRose?: InputMaybe<StringFilter>;
  sub1?: InputMaybe<StringFilter>;
  sub2?: InputMaybe<StringFilter>;
  ctaPrimary?: InputMaybe<StringFilter>;
  ctaSecondary?: InputMaybe<StringFilter>;
  stats?: InputMaybe<HeroStatsFilter>;
};

export type HeroConnectionEdges = {
  __typename?: 'HeroConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Hero>;
};

export type HeroConnection = Connection & {
  __typename?: 'HeroConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HeroConnectionEdges>>>;
};

export type Service = Node & Document & {
  __typename?: 'Service';
  slug: Scalars['String']['output'];
  name: Scalars['String']['output'];
  tag?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  iconKey?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ServiceFilter = {
  slug?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  tag?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  iconKey?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type ServiceConnectionEdges = {
  __typename?: 'ServiceConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Service>;
};

export type ServiceConnection = Connection & {
  __typename?: 'ServiceConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServiceConnectionEdges>>>;
};

export type Testimonial = Node & Document & {
  __typename?: 'Testimonial';
  name: Scalars['String']['output'];
  role?: Maybe<Scalars['String']['output']>;
  metric?: Maybe<Scalars['String']['output']>;
  logo?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TestimonialFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  metric?: InputMaybe<StringFilter>;
  logo?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type TestimonialConnectionEdges = {
  __typename?: 'TestimonialConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Testimonial>;
};

export type TestimonialConnection = Connection & {
  __typename?: 'TestimonialConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TestimonialConnectionEdges>>>;
};

export type PainCard = Node & Document & {
  __typename?: 'PainCard';
  title: Scalars['String']['output'];
  desc?: Maybe<Scalars['String']['output']>;
  iconKey?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PainCardFilter = {
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  iconKey?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type PainCardConnectionEdges = {
  __typename?: 'PainCardConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<PainCard>;
};

export type PainCardConnection = Connection & {
  __typename?: 'PainCardConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PainCardConnectionEdges>>>;
};

export type Result = Node & Document & {
  __typename?: 'Result';
  metricNumber: Scalars['String']['output'];
  metricPrefix?: Maybe<Scalars['String']['output']>;
  metricSuffix?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ResultFilter = {
  metricNumber?: InputMaybe<StringFilter>;
  metricPrefix?: InputMaybe<StringFilter>;
  metricSuffix?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type ResultConnectionEdges = {
  __typename?: 'ResultConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Result>;
};

export type ResultConnection = Connection & {
  __typename?: 'ResultConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ResultConnectionEdges>>>;
};

export type TechCard = Node & Document & {
  __typename?: 'TechCard';
  label: Scalars['String']['output'];
  name?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  iconKey?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TechCardFilter = {
  label?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  iconKey?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type TechCardConnectionEdges = {
  __typename?: 'TechCardConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<TechCard>;
};

export type TechCardConnection = Connection & {
  __typename?: 'TechCardConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TechCardConnectionEdges>>>;
};

export type SistemaCard = Node & Document & {
  __typename?: 'SistemaCard';
  label: Scalars['String']['output'];
  name?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  iconKey?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SistemaCardFilter = {
  label?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  iconKey?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type SistemaCardConnectionEdges = {
  __typename?: 'SistemaCardConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SistemaCard>;
};

export type SistemaCardConnection = Connection & {
  __typename?: 'SistemaCardConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SistemaCardConnectionEdges>>>;
};

export type ProcesoStep = Node & Document & {
  __typename?: 'ProcesoStep';
  num: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  tag?: Maybe<Scalars['String']['output']>;
  active?: Maybe<Scalars['Boolean']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ProcesoStepFilter = {
  num?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  tag?: InputMaybe<StringFilter>;
  active?: InputMaybe<BooleanFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type ProcesoStepConnectionEdges = {
  __typename?: 'ProcesoStepConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ProcesoStep>;
};

export type ProcesoStepConnection = Connection & {
  __typename?: 'ProcesoStepConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProcesoStepConnectionEdges>>>;
};

export type Contact = Node & Document & {
  __typename?: 'Contact';
  sectionTitle?: Maybe<Scalars['String']['output']>;
  sectionDesc?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  trustItems?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  objectives?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactFilter = {
  sectionTitle?: InputMaybe<StringFilter>;
  sectionDesc?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  trustItems?: InputMaybe<StringFilter>;
  objectives?: InputMaybe<StringFilter>;
};

export type ContactConnectionEdges = {
  __typename?: 'ContactConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contact>;
};

export type ContactConnection = Connection & {
  __typename?: 'ContactConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHero: Hero;
  createHero: Hero;
  updateService: Service;
  createService: Service;
  updateTestimonial: Testimonial;
  createTestimonial: Testimonial;
  updatePainCard: PainCard;
  createPainCard: PainCard;
  updateResult: Result;
  createResult: Result;
  updateTechCard: TechCard;
  createTechCard: TechCard;
  updateSistemaCard: SistemaCard;
  createSistemaCard: SistemaCard;
  updateProcesoStep: ProcesoStep;
  createProcesoStep: ProcesoStep;
  updateContact: Contact;
  createContact: Contact;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHeroArgs = {
  relativePath: Scalars['String']['input'];
  params: HeroMutation;
};


export type MutationCreateHeroArgs = {
  relativePath: Scalars['String']['input'];
  params: HeroMutation;
};


export type MutationUpdateServiceArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceMutation;
};


export type MutationCreateServiceArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceMutation;
};


export type MutationUpdateTestimonialArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialMutation;
};


export type MutationCreateTestimonialArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialMutation;
};


export type MutationUpdatePainCardArgs = {
  relativePath: Scalars['String']['input'];
  params: PainCardMutation;
};


export type MutationCreatePainCardArgs = {
  relativePath: Scalars['String']['input'];
  params: PainCardMutation;
};


export type MutationUpdateResultArgs = {
  relativePath: Scalars['String']['input'];
  params: ResultMutation;
};


export type MutationCreateResultArgs = {
  relativePath: Scalars['String']['input'];
  params: ResultMutation;
};


export type MutationUpdateTechCardArgs = {
  relativePath: Scalars['String']['input'];
  params: TechCardMutation;
};


export type MutationCreateTechCardArgs = {
  relativePath: Scalars['String']['input'];
  params: TechCardMutation;
};


export type MutationUpdateSistemaCardArgs = {
  relativePath: Scalars['String']['input'];
  params: SistemaCardMutation;
};


export type MutationCreateSistemaCardArgs = {
  relativePath: Scalars['String']['input'];
  params: SistemaCardMutation;
};


export type MutationUpdateProcesoStepArgs = {
  relativePath: Scalars['String']['input'];
  params: ProcesoStepMutation;
};


export type MutationCreateProcesoStepArgs = {
  relativePath: Scalars['String']['input'];
  params: ProcesoStepMutation;
};


export type MutationUpdateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationCreateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};

export type DocumentUpdateMutation = {
  hero?: InputMaybe<HeroMutation>;
  service?: InputMaybe<ServiceMutation>;
  testimonial?: InputMaybe<TestimonialMutation>;
  painCard?: InputMaybe<PainCardMutation>;
  result?: InputMaybe<ResultMutation>;
  techCard?: InputMaybe<TechCardMutation>;
  sistemaCard?: InputMaybe<SistemaCardMutation>;
  procesoStep?: InputMaybe<ProcesoStepMutation>;
  contact?: InputMaybe<ContactMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  hero?: InputMaybe<HeroMutation>;
  service?: InputMaybe<ServiceMutation>;
  testimonial?: InputMaybe<TestimonialMutation>;
  painCard?: InputMaybe<PainCardMutation>;
  result?: InputMaybe<ResultMutation>;
  techCard?: InputMaybe<TechCardMutation>;
  sistemaCard?: InputMaybe<SistemaCardMutation>;
  procesoStep?: InputMaybe<ProcesoStepMutation>;
  contact?: InputMaybe<ContactMutation>;
};

export type HeroStatsMutation = {
  number?: InputMaybe<Scalars['String']['input']>;
  suffix?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type HeroMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  accentBlue?: InputMaybe<Scalars['String']['input']>;
  accentRose?: InputMaybe<Scalars['String']['input']>;
  sub1?: InputMaybe<Scalars['String']['input']>;
  sub2?: InputMaybe<Scalars['String']['input']>;
  ctaPrimary?: InputMaybe<Scalars['String']['input']>;
  ctaSecondary?: InputMaybe<Scalars['String']['input']>;
  stats?: InputMaybe<Array<InputMaybe<HeroStatsMutation>>>;
};

export type ServiceMutation = {
  slug?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  tag?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  iconKey?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type TestimonialMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  metric?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type PainCardMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  iconKey?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type ResultMutation = {
  metricNumber?: InputMaybe<Scalars['String']['input']>;
  metricPrefix?: InputMaybe<Scalars['String']['input']>;
  metricSuffix?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type TechCardMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  iconKey?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type SistemaCardMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  iconKey?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type ProcesoStepMutation = {
  num?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  tag?: InputMaybe<Scalars['String']['input']>;
  active?: InputMaybe<Scalars['Boolean']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type ContactMutation = {
  sectionTitle?: InputMaybe<Scalars['String']['input']>;
  sectionDesc?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  trustItems?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  objectives?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HeroPartsFragment = { __typename: 'Hero', eyebrow?: string | null, title?: string | null, accentBlue?: string | null, accentRose?: string | null, sub1?: string | null, sub2?: string | null, ctaPrimary?: string | null, ctaSecondary?: string | null, stats?: Array<{ __typename: 'HeroStats', number?: string | null, suffix?: string | null, label?: string | null } | null> | null };

export type ServicePartsFragment = { __typename: 'Service', slug: string, name: string, tag?: string | null, desc?: string | null, iconKey?: string | null, order?: number | null };

export type TestimonialPartsFragment = { __typename: 'Testimonial', name: string, role?: string | null, metric?: string | null, logo?: string | null, text?: string | null, order?: number | null };

export type PainCardPartsFragment = { __typename: 'PainCard', title: string, desc?: string | null, iconKey?: string | null, order?: number | null };

export type ResultPartsFragment = { __typename: 'Result', metricNumber: string, metricPrefix?: string | null, metricSuffix?: string | null, label?: string | null, desc?: string | null, order?: number | null };

export type TechCardPartsFragment = { __typename: 'TechCard', label: string, name?: string | null, desc?: string | null, iconKey?: string | null, order?: number | null };

export type SistemaCardPartsFragment = { __typename: 'SistemaCard', label: string, name?: string | null, desc?: string | null, iconKey?: string | null, order?: number | null };

export type ProcesoStepPartsFragment = { __typename: 'ProcesoStep', num: string, title?: string | null, desc?: string | null, tag?: string | null, active?: boolean | null, order?: number | null };

export type ContactPartsFragment = { __typename: 'Contact', sectionTitle?: string | null, sectionDesc?: string | null, tagline?: string | null, trustItems?: Array<string | null> | null, objectives?: Array<string | null> | null };

export type HeroQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HeroQuery = { __typename?: 'Query', hero: { __typename: 'Hero', id: string, eyebrow?: string | null, title?: string | null, accentBlue?: string | null, accentRose?: string | null, sub1?: string | null, sub2?: string | null, ctaPrimary?: string | null, ctaSecondary?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats?: Array<{ __typename: 'HeroStats', number?: string | null, suffix?: string | null, label?: string | null } | null> | null } };

export type HeroConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HeroFilter>;
}>;


export type HeroConnectionQuery = { __typename?: 'Query', heroConnection: { __typename?: 'HeroConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HeroConnectionEdges', cursor: string, node?: { __typename: 'Hero', id: string, eyebrow?: string | null, title?: string | null, accentBlue?: string | null, accentRose?: string | null, sub1?: string | null, sub2?: string | null, ctaPrimary?: string | null, ctaSecondary?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats?: Array<{ __typename: 'HeroStats', number?: string | null, suffix?: string | null, label?: string | null } | null> | null } | null } | null> | null } };

export type ServiceQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServiceQuery = { __typename?: 'Query', service: { __typename: 'Service', id: string, slug: string, name: string, tag?: string | null, desc?: string | null, iconKey?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ServiceConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiceFilter>;
}>;


export type ServiceConnectionQuery = { __typename?: 'Query', serviceConnection: { __typename?: 'ServiceConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServiceConnectionEdges', cursor: string, node?: { __typename: 'Service', id: string, slug: string, name: string, tag?: string | null, desc?: string | null, iconKey?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TestimonialQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TestimonialQuery = { __typename?: 'Query', testimonial: { __typename: 'Testimonial', id: string, name: string, role?: string | null, metric?: string | null, logo?: string | null, text?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TestimonialConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialFilter>;
}>;


export type TestimonialConnectionQuery = { __typename?: 'Query', testimonialConnection: { __typename?: 'TestimonialConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TestimonialConnectionEdges', cursor: string, node?: { __typename: 'Testimonial', id: string, name: string, role?: string | null, metric?: string | null, logo?: string | null, text?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PainCardQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PainCardQuery = { __typename?: 'Query', painCard: { __typename: 'PainCard', id: string, title: string, desc?: string | null, iconKey?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PainCardConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PainCardFilter>;
}>;


export type PainCardConnectionQuery = { __typename?: 'Query', painCardConnection: { __typename?: 'PainCardConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PainCardConnectionEdges', cursor: string, node?: { __typename: 'PainCard', id: string, title: string, desc?: string | null, iconKey?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ResultQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ResultQuery = { __typename?: 'Query', result: { __typename: 'Result', id: string, metricNumber: string, metricPrefix?: string | null, metricSuffix?: string | null, label?: string | null, desc?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ResultConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResultFilter>;
}>;


export type ResultConnectionQuery = { __typename?: 'Query', resultConnection: { __typename?: 'ResultConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ResultConnectionEdges', cursor: string, node?: { __typename: 'Result', id: string, metricNumber: string, metricPrefix?: string | null, metricSuffix?: string | null, label?: string | null, desc?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TechCardQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TechCardQuery = { __typename?: 'Query', techCard: { __typename: 'TechCard', id: string, label: string, name?: string | null, desc?: string | null, iconKey?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TechCardConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TechCardFilter>;
}>;


export type TechCardConnectionQuery = { __typename?: 'Query', techCardConnection: { __typename?: 'TechCardConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TechCardConnectionEdges', cursor: string, node?: { __typename: 'TechCard', id: string, label: string, name?: string | null, desc?: string | null, iconKey?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SistemaCardQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SistemaCardQuery = { __typename?: 'Query', sistemaCard: { __typename: 'SistemaCard', id: string, label: string, name?: string | null, desc?: string | null, iconKey?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SistemaCardConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SistemaCardFilter>;
}>;


export type SistemaCardConnectionQuery = { __typename?: 'Query', sistemaCardConnection: { __typename?: 'SistemaCardConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SistemaCardConnectionEdges', cursor: string, node?: { __typename: 'SistemaCard', id: string, label: string, name?: string | null, desc?: string | null, iconKey?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ProcesoStepQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProcesoStepQuery = { __typename?: 'Query', procesoStep: { __typename: 'ProcesoStep', id: string, num: string, title?: string | null, desc?: string | null, tag?: string | null, active?: boolean | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ProcesoStepConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProcesoStepFilter>;
}>;


export type ProcesoStepConnectionQuery = { __typename?: 'Query', procesoStepConnection: { __typename?: 'ProcesoStepConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProcesoStepConnectionEdges', cursor: string, node?: { __typename: 'ProcesoStep', id: string, num: string, title?: string | null, desc?: string | null, tag?: string | null, active?: boolean | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ContactQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactQuery = { __typename?: 'Query', contact: { __typename: 'Contact', id: string, sectionTitle?: string | null, sectionDesc?: string | null, tagline?: string | null, trustItems?: Array<string | null> | null, objectives?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ContactConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
}>;


export type ContactConnectionQuery = { __typename?: 'Query', contactConnection: { __typename?: 'ContactConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactConnectionEdges', cursor: string, node?: { __typename: 'Contact', id: string, sectionTitle?: string | null, sectionDesc?: string | null, tagline?: string | null, trustItems?: Array<string | null> | null, objectives?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const HeroPartsFragmentDoc = gql`
    fragment HeroParts on Hero {
  __typename
  eyebrow
  title
  accentBlue
  accentRose
  sub1
  sub2
  ctaPrimary
  ctaSecondary
  stats {
    __typename
    number
    suffix
    label
  }
}
    `;
export const ServicePartsFragmentDoc = gql`
    fragment ServiceParts on Service {
  __typename
  slug
  name
  tag
  desc
  iconKey
  order
}
    `;
export const TestimonialPartsFragmentDoc = gql`
    fragment TestimonialParts on Testimonial {
  __typename
  name
  role
  metric
  logo
  text
  order
}
    `;
export const PainCardPartsFragmentDoc = gql`
    fragment PainCardParts on PainCard {
  __typename
  title
  desc
  iconKey
  order
}
    `;
export const ResultPartsFragmentDoc = gql`
    fragment ResultParts on Result {
  __typename
  metricNumber
  metricPrefix
  metricSuffix
  label
  desc
  order
}
    `;
export const TechCardPartsFragmentDoc = gql`
    fragment TechCardParts on TechCard {
  __typename
  label
  name
  desc
  iconKey
  order
}
    `;
export const SistemaCardPartsFragmentDoc = gql`
    fragment SistemaCardParts on SistemaCard {
  __typename
  label
  name
  desc
  iconKey
  order
}
    `;
export const ProcesoStepPartsFragmentDoc = gql`
    fragment ProcesoStepParts on ProcesoStep {
  __typename
  num
  title
  desc
  tag
  active
  order
}
    `;
export const ContactPartsFragmentDoc = gql`
    fragment ContactParts on Contact {
  __typename
  sectionTitle
  sectionDesc
  tagline
  trustItems
  objectives
}
    `;
export const HeroDocument = gql`
    query hero($relativePath: String!) {
  hero(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HeroParts
  }
}
    ${HeroPartsFragmentDoc}`;
export const HeroConnectionDocument = gql`
    query heroConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HeroFilter) {
  heroConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HeroParts
      }
    }
  }
}
    ${HeroPartsFragmentDoc}`;
export const ServiceDocument = gql`
    query service($relativePath: String!) {
  service(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServiceParts
  }
}
    ${ServicePartsFragmentDoc}`;
export const ServiceConnectionDocument = gql`
    query serviceConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServiceFilter) {
  serviceConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServiceParts
      }
    }
  }
}
    ${ServicePartsFragmentDoc}`;
export const TestimonialDocument = gql`
    query testimonial($relativePath: String!) {
  testimonial(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TestimonialParts
  }
}
    ${TestimonialPartsFragmentDoc}`;
export const TestimonialConnectionDocument = gql`
    query testimonialConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TestimonialFilter) {
  testimonialConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TestimonialParts
      }
    }
  }
}
    ${TestimonialPartsFragmentDoc}`;
export const PainCardDocument = gql`
    query painCard($relativePath: String!) {
  painCard(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PainCardParts
  }
}
    ${PainCardPartsFragmentDoc}`;
export const PainCardConnectionDocument = gql`
    query painCardConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PainCardFilter) {
  painCardConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PainCardParts
      }
    }
  }
}
    ${PainCardPartsFragmentDoc}`;
export const ResultDocument = gql`
    query result($relativePath: String!) {
  result(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ResultParts
  }
}
    ${ResultPartsFragmentDoc}`;
export const ResultConnectionDocument = gql`
    query resultConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ResultFilter) {
  resultConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ResultParts
      }
    }
  }
}
    ${ResultPartsFragmentDoc}`;
export const TechCardDocument = gql`
    query techCard($relativePath: String!) {
  techCard(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TechCardParts
  }
}
    ${TechCardPartsFragmentDoc}`;
export const TechCardConnectionDocument = gql`
    query techCardConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TechCardFilter) {
  techCardConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TechCardParts
      }
    }
  }
}
    ${TechCardPartsFragmentDoc}`;
export const SistemaCardDocument = gql`
    query sistemaCard($relativePath: String!) {
  sistemaCard(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SistemaCardParts
  }
}
    ${SistemaCardPartsFragmentDoc}`;
export const SistemaCardConnectionDocument = gql`
    query sistemaCardConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SistemaCardFilter) {
  sistemaCardConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SistemaCardParts
      }
    }
  }
}
    ${SistemaCardPartsFragmentDoc}`;
export const ProcesoStepDocument = gql`
    query procesoStep($relativePath: String!) {
  procesoStep(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProcesoStepParts
  }
}
    ${ProcesoStepPartsFragmentDoc}`;
export const ProcesoStepConnectionDocument = gql`
    query procesoStepConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProcesoStepFilter) {
  procesoStepConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProcesoStepParts
      }
    }
  }
}
    ${ProcesoStepPartsFragmentDoc}`;
export const ContactDocument = gql`
    query contact($relativePath: String!) {
  contact(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactParts
  }
}
    ${ContactPartsFragmentDoc}`;
export const ContactConnectionDocument = gql`
    query contactConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactFilter) {
  contactConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactParts
      }
    }
  }
}
    ${ContactPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      hero(variables: HeroQueryVariables, options?: C): Promise<{data: HeroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroQueryVariables, query: string}> {
        return requester<{data: HeroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroQueryVariables, query: string}, HeroQueryVariables>(HeroDocument, variables, options);
      },
    heroConnection(variables?: HeroConnectionQueryVariables, options?: C): Promise<{data: HeroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroConnectionQueryVariables, query: string}> {
        return requester<{data: HeroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroConnectionQueryVariables, query: string}, HeroConnectionQueryVariables>(HeroConnectionDocument, variables, options);
      },
    service(variables: ServiceQueryVariables, options?: C): Promise<{data: ServiceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceQueryVariables, query: string}> {
        return requester<{data: ServiceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceQueryVariables, query: string}, ServiceQueryVariables>(ServiceDocument, variables, options);
      },
    serviceConnection(variables?: ServiceConnectionQueryVariables, options?: C): Promise<{data: ServiceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceConnectionQueryVariables, query: string}> {
        return requester<{data: ServiceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceConnectionQueryVariables, query: string}, ServiceConnectionQueryVariables>(ServiceConnectionDocument, variables, options);
      },
    testimonial(variables: TestimonialQueryVariables, options?: C): Promise<{data: TestimonialQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialQueryVariables, query: string}> {
        return requester<{data: TestimonialQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialQueryVariables, query: string}, TestimonialQueryVariables>(TestimonialDocument, variables, options);
      },
    testimonialConnection(variables?: TestimonialConnectionQueryVariables, options?: C): Promise<{data: TestimonialConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialConnectionQueryVariables, query: string}> {
        return requester<{data: TestimonialConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialConnectionQueryVariables, query: string}, TestimonialConnectionQueryVariables>(TestimonialConnectionDocument, variables, options);
      },
    painCard(variables: PainCardQueryVariables, options?: C): Promise<{data: PainCardQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PainCardQueryVariables, query: string}> {
        return requester<{data: PainCardQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PainCardQueryVariables, query: string}, PainCardQueryVariables>(PainCardDocument, variables, options);
      },
    painCardConnection(variables?: PainCardConnectionQueryVariables, options?: C): Promise<{data: PainCardConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PainCardConnectionQueryVariables, query: string}> {
        return requester<{data: PainCardConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PainCardConnectionQueryVariables, query: string}, PainCardConnectionQueryVariables>(PainCardConnectionDocument, variables, options);
      },
    result(variables: ResultQueryVariables, options?: C): Promise<{data: ResultQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResultQueryVariables, query: string}> {
        return requester<{data: ResultQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResultQueryVariables, query: string}, ResultQueryVariables>(ResultDocument, variables, options);
      },
    resultConnection(variables?: ResultConnectionQueryVariables, options?: C): Promise<{data: ResultConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResultConnectionQueryVariables, query: string}> {
        return requester<{data: ResultConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResultConnectionQueryVariables, query: string}, ResultConnectionQueryVariables>(ResultConnectionDocument, variables, options);
      },
    techCard(variables: TechCardQueryVariables, options?: C): Promise<{data: TechCardQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TechCardQueryVariables, query: string}> {
        return requester<{data: TechCardQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TechCardQueryVariables, query: string}, TechCardQueryVariables>(TechCardDocument, variables, options);
      },
    techCardConnection(variables?: TechCardConnectionQueryVariables, options?: C): Promise<{data: TechCardConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TechCardConnectionQueryVariables, query: string}> {
        return requester<{data: TechCardConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TechCardConnectionQueryVariables, query: string}, TechCardConnectionQueryVariables>(TechCardConnectionDocument, variables, options);
      },
    sistemaCard(variables: SistemaCardQueryVariables, options?: C): Promise<{data: SistemaCardQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SistemaCardQueryVariables, query: string}> {
        return requester<{data: SistemaCardQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SistemaCardQueryVariables, query: string}, SistemaCardQueryVariables>(SistemaCardDocument, variables, options);
      },
    sistemaCardConnection(variables?: SistemaCardConnectionQueryVariables, options?: C): Promise<{data: SistemaCardConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SistemaCardConnectionQueryVariables, query: string}> {
        return requester<{data: SistemaCardConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SistemaCardConnectionQueryVariables, query: string}, SistemaCardConnectionQueryVariables>(SistemaCardConnectionDocument, variables, options);
      },
    procesoStep(variables: ProcesoStepQueryVariables, options?: C): Promise<{data: ProcesoStepQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProcesoStepQueryVariables, query: string}> {
        return requester<{data: ProcesoStepQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProcesoStepQueryVariables, query: string}, ProcesoStepQueryVariables>(ProcesoStepDocument, variables, options);
      },
    procesoStepConnection(variables?: ProcesoStepConnectionQueryVariables, options?: C): Promise<{data: ProcesoStepConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProcesoStepConnectionQueryVariables, query: string}> {
        return requester<{data: ProcesoStepConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProcesoStepConnectionQueryVariables, query: string}, ProcesoStepConnectionQueryVariables>(ProcesoStepConnectionDocument, variables, options);
      },
    contact(variables: ContactQueryVariables, options?: C): Promise<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}> {
        return requester<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}, ContactQueryVariables>(ContactDocument, variables, options);
      },
    contactConnection(variables?: ContactConnectionQueryVariables, options?: C): Promise<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}> {
        return requester<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}, ContactConnectionQueryVariables>(ContactConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  